name: UI tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Gel
        uses: geldata/setup-gel@v1
        with:
          server-version: nightly

      - name: Install dev deps
        working-directory: web
        run: |
          yarn

      - name: Install Playwright Browsers
        working-directory: web
        run: |
          yarn playwright install --with-deps chromium

      - name: Run tests
        working-directory: web
        run: |
          yarn test
